os: linux
dist: focal
language: java
jdk:
  - openjdk8
jobs:
  include: 
  - name: “test” # existing functionality
    script: # existing functionality
      - java -version
  - name: “sbom”
    addons:
      sbom:
        on:
          branch: 'main'
          pr: false
        run_phase: "after_success" # 
        output_format: "cyclonedx-json" # 
        output_dir: "test" # 
        input_dir: "java" # 
