os: linux
dist: focal
language: java
jdk:
  - openjdk8
jobs:
  include: 
  - name: “test” # existing functionality
    script: # existing functionality
      - java -version
  - name: “sbom”
    script: # existing functionality
      - java -version
    addons:
      sbom:
        on:
          branch: 'main'
          pr: true
        run_phase: "after_failure" # 
        output_format: "cyclonedx-json" # 
        output_dir: "/test" # 
        input_dir: "/java" # 
